# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vfl_client_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vfl_client_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18vfl_client_service.proto\"a\n\x1flr_train_batch_gradient_request\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x02 \x01(\x05\x12\x16\n\x0e\x62\x61tch_gradient\x18\x03 \x03(\x02\"K\n lr_train_batch_gradient_response\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x14\n\x0creceive_flag\x18\x02 \x01(\x08\"N\n\x16rsa_public_key_request\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x0c\n\x04pk_N\x18\x03 \x01(\x0c\x12\x0c\n\x04pk_e\x18\x04 \x01(\x05\"H\n\x17rsa_public_key_response\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x13\n\x0brecv_status\x18\x03 \x01(\x08\"V\n\x1bsend_client_enc_ids_request\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x1d\n\x15\x63lient_enc_ids_pk_str\x18\x03 \x03(\t\"M\n\x1csend_client_enc_ids_response\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x13\n\x0brecv_status\x18\x03 \x01(\x08\"\x7f\n.send_server_enc_ids_and_client_dec_ids_request\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x16\n\x0e\x63lient_dec_ids\x18\x03 \x03(\t\x12\x1b\n\x13server_hash_enc_ids\x18\x04 \x03(\t\"\x98\x01\n/send_server_enc_ids_and_client_dec_ids_response\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\"\n\x1a\x63lient_dec_ids_recv_status\x18\x03 \x01(\x08\x12\'\n\x1fserver_hash_enc_ids_recv_status\x18\x04 \x01(\x08\x32\xa3\x03\n\x10VFLClientService\x12\x63\n\x1csend_lr_train_batch_gradient\x12 .lr_train_batch_gradient_request\x1a!.lr_train_batch_gradient_response\x12H\n\x13send_rsa_public_key\x12\x17.rsa_public_key_request\x1a\x18.rsa_public_key_response\x12R\n\x13send_client_enc_ids\x12\x1c.send_client_enc_ids_request\x1a\x1d.send_client_enc_ids_response\x12\x8b\x01\n&send_server_enc_ids_and_client_dec_ids\x12/.send_server_enc_ids_and_client_dec_ids_request\x1a\x30.send_server_enc_ids_and_client_dec_ids_responseb\x06proto3'
)




_LR_TRAIN_BATCH_GRADIENT_REQUEST = _descriptor.Descriptor(
  name='lr_train_batch_gradient_request',
  full_name='lr_train_batch_gradient_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='lr_train_batch_gradient_request.server_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_index', full_name='lr_train_batch_gradient_request.batch_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_gradient', full_name='lr_train_batch_gradient_request.batch_gradient', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=125,
)


_LR_TRAIN_BATCH_GRADIENT_RESPONSE = _descriptor.Descriptor(
  name='lr_train_batch_gradient_response',
  full_name='lr_train_batch_gradient_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='lr_train_batch_gradient_response.server_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receive_flag', full_name='lr_train_batch_gradient_response.receive_flag', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=202,
)


_RSA_PUBLIC_KEY_REQUEST = _descriptor.Descriptor(
  name='rsa_public_key_request',
  full_name='rsa_public_key_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='rsa_public_key_request.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='rsa_public_key_request.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pk_N', full_name='rsa_public_key_request.pk_N', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pk_e', full_name='rsa_public_key_request.pk_e', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=282,
)


_RSA_PUBLIC_KEY_RESPONSE = _descriptor.Descriptor(
  name='rsa_public_key_response',
  full_name='rsa_public_key_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='rsa_public_key_response.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='rsa_public_key_response.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recv_status', full_name='rsa_public_key_response.recv_status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=356,
)


_SEND_CLIENT_ENC_IDS_REQUEST = _descriptor.Descriptor(
  name='send_client_enc_ids_request',
  full_name='send_client_enc_ids_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='send_client_enc_ids_request.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='send_client_enc_ids_request.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_enc_ids_pk_str', full_name='send_client_enc_ids_request.client_enc_ids_pk_str', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=444,
)


_SEND_CLIENT_ENC_IDS_RESPONSE = _descriptor.Descriptor(
  name='send_client_enc_ids_response',
  full_name='send_client_enc_ids_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='send_client_enc_ids_response.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='send_client_enc_ids_response.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recv_status', full_name='send_client_enc_ids_response.recv_status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=523,
)


_SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_REQUEST = _descriptor.Descriptor(
  name='send_server_enc_ids_and_client_dec_ids_request',
  full_name='send_server_enc_ids_and_client_dec_ids_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='send_server_enc_ids_and_client_dec_ids_request.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='send_server_enc_ids_and_client_dec_ids_request.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_dec_ids', full_name='send_server_enc_ids_and_client_dec_ids_request.client_dec_ids', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_hash_enc_ids', full_name='send_server_enc_ids_and_client_dec_ids_request.server_hash_enc_ids', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=652,
)


_SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_RESPONSE = _descriptor.Descriptor(
  name='send_server_enc_ids_and_client_dec_ids_response',
  full_name='send_server_enc_ids_and_client_dec_ids_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='send_server_enc_ids_and_client_dec_ids_response.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='send_server_enc_ids_and_client_dec_ids_response.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_dec_ids_recv_status', full_name='send_server_enc_ids_and_client_dec_ids_response.client_dec_ids_recv_status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_hash_enc_ids_recv_status', full_name='send_server_enc_ids_and_client_dec_ids_response.server_hash_enc_ids_recv_status', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=807,
)

DESCRIPTOR.message_types_by_name['lr_train_batch_gradient_request'] = _LR_TRAIN_BATCH_GRADIENT_REQUEST
DESCRIPTOR.message_types_by_name['lr_train_batch_gradient_response'] = _LR_TRAIN_BATCH_GRADIENT_RESPONSE
DESCRIPTOR.message_types_by_name['rsa_public_key_request'] = _RSA_PUBLIC_KEY_REQUEST
DESCRIPTOR.message_types_by_name['rsa_public_key_response'] = _RSA_PUBLIC_KEY_RESPONSE
DESCRIPTOR.message_types_by_name['send_client_enc_ids_request'] = _SEND_CLIENT_ENC_IDS_REQUEST
DESCRIPTOR.message_types_by_name['send_client_enc_ids_response'] = _SEND_CLIENT_ENC_IDS_RESPONSE
DESCRIPTOR.message_types_by_name['send_server_enc_ids_and_client_dec_ids_request'] = _SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_REQUEST
DESCRIPTOR.message_types_by_name['send_server_enc_ids_and_client_dec_ids_response'] = _SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

lr_train_batch_gradient_request = _reflection.GeneratedProtocolMessageType('lr_train_batch_gradient_request', (_message.Message,), {
  'DESCRIPTOR' : _LR_TRAIN_BATCH_GRADIENT_REQUEST,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:lr_train_batch_gradient_request)
  })
_sym_db.RegisterMessage(lr_train_batch_gradient_request)

lr_train_batch_gradient_response = _reflection.GeneratedProtocolMessageType('lr_train_batch_gradient_response', (_message.Message,), {
  'DESCRIPTOR' : _LR_TRAIN_BATCH_GRADIENT_RESPONSE,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:lr_train_batch_gradient_response)
  })
_sym_db.RegisterMessage(lr_train_batch_gradient_response)

rsa_public_key_request = _reflection.GeneratedProtocolMessageType('rsa_public_key_request', (_message.Message,), {
  'DESCRIPTOR' : _RSA_PUBLIC_KEY_REQUEST,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rsa_public_key_request)
  })
_sym_db.RegisterMessage(rsa_public_key_request)

rsa_public_key_response = _reflection.GeneratedProtocolMessageType('rsa_public_key_response', (_message.Message,), {
  'DESCRIPTOR' : _RSA_PUBLIC_KEY_RESPONSE,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rsa_public_key_response)
  })
_sym_db.RegisterMessage(rsa_public_key_response)

send_client_enc_ids_request = _reflection.GeneratedProtocolMessageType('send_client_enc_ids_request', (_message.Message,), {
  'DESCRIPTOR' : _SEND_CLIENT_ENC_IDS_REQUEST,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:send_client_enc_ids_request)
  })
_sym_db.RegisterMessage(send_client_enc_ids_request)

send_client_enc_ids_response = _reflection.GeneratedProtocolMessageType('send_client_enc_ids_response', (_message.Message,), {
  'DESCRIPTOR' : _SEND_CLIENT_ENC_IDS_RESPONSE,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:send_client_enc_ids_response)
  })
_sym_db.RegisterMessage(send_client_enc_ids_response)

send_server_enc_ids_and_client_dec_ids_request = _reflection.GeneratedProtocolMessageType('send_server_enc_ids_and_client_dec_ids_request', (_message.Message,), {
  'DESCRIPTOR' : _SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_REQUEST,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:send_server_enc_ids_and_client_dec_ids_request)
  })
_sym_db.RegisterMessage(send_server_enc_ids_and_client_dec_ids_request)

send_server_enc_ids_and_client_dec_ids_response = _reflection.GeneratedProtocolMessageType('send_server_enc_ids_and_client_dec_ids_response', (_message.Message,), {
  'DESCRIPTOR' : _SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_RESPONSE,
  '__module__' : 'vfl_client_service_pb2'
  # @@protoc_insertion_point(class_scope:send_server_enc_ids_and_client_dec_ids_response)
  })
_sym_db.RegisterMessage(send_server_enc_ids_and_client_dec_ids_response)



_VFLCLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='VFLClientService',
  full_name='VFLClientService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=810,
  serialized_end=1229,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_lr_train_batch_gradient',
    full_name='VFLClientService.send_lr_train_batch_gradient',
    index=0,
    containing_service=None,
    input_type=_LR_TRAIN_BATCH_GRADIENT_REQUEST,
    output_type=_LR_TRAIN_BATCH_GRADIENT_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_rsa_public_key',
    full_name='VFLClientService.send_rsa_public_key',
    index=1,
    containing_service=None,
    input_type=_RSA_PUBLIC_KEY_REQUEST,
    output_type=_RSA_PUBLIC_KEY_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_client_enc_ids',
    full_name='VFLClientService.send_client_enc_ids',
    index=2,
    containing_service=None,
    input_type=_SEND_CLIENT_ENC_IDS_REQUEST,
    output_type=_SEND_CLIENT_ENC_IDS_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_server_enc_ids_and_client_dec_ids',
    full_name='VFLClientService.send_server_enc_ids_and_client_dec_ids',
    index=3,
    containing_service=None,
    input_type=_SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_REQUEST,
    output_type=_SEND_SERVER_ENC_IDS_AND_CLIENT_DEC_IDS_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VFLCLIENTSERVICE)

DESCRIPTOR.services_by_name['VFLClientService'] = _VFLCLIENTSERVICE

# @@protoc_insertion_point(module_scope)
